- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - firewall
    - always

    - include_tasks: setup-{{ ansible_facts.os_family }}-{{ _firewall_name }}.yml
  tags
    - firewall

- include_tasks: configure-{{ _firewall_name }}.yml
  tags:
    - firewall
    - firewall_config
    - fwconfig
